//******************************************************************************
//
// Copyright 2026 IHP PDK Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//******************************************************************************

//******************************************************************************
// Resistor paramsets
//
// Adapted from `ngspice/models/resistor_mod.lib`
//
// Paramsets are organized by resistor type in the included files.
//******************************************************************************

`pragma modelgen nogen-module
// Resistor models
`include "r3_cmc.va"
`include "resistor.va"

// Device-specific paramsets
`include "paramsets/resistor_parasitics.va"
`include "paramsets/resistor_rsil.va"
`include "paramsets/resistor_rhigh.va"
`include "paramsets/resistor_rppd.va"
