//******************************************************************************
//
// Copyright 2026 IHP PDK Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//******************************************************************************

//******************************************************************************
// SG13G2_HBT paramsets
//
// Adapted from `ngspice/models/sg13g2_hbt_mod*.lib` modelcards
//
// Paramsets for HBT device variants are included below.
//******************************************************************************

`pragma modelgen nogen-module
`include "vbic_1p3.va"
//`include "bjt.va"

`include "paramsets/sg13g2_hbt_npn13G2.va"
`include "paramsets/sg13g2_hbt_npn13G2l.va"
`include "paramsets/sg13g2_hbt_npn13G2v.va"
//`include "paramsets/pnpMPA.va" // TODO: compiles but does not simulate


