//******************************************************************************
//                                                                             *
// Library:      SG13G2_dev                                                    *
// Technologies: SG13G2                                                        *
//                                                                             *
// Model:        PSP 108.3.2                                                   *
// Revision:     210511                                                        *
//                                                                             *
//******************************************************************************
//                                                                             *
// Copyright 2026 IHP PDK Authors                                              *
//                                                                             *
// Licensed under the Apache License, Version 2.0 (the "License");             *
// you may not use this file except in compliance with the License.            *
// You may obtain a copy of the License at                                     *
//                                                                             *
//     https://www.apache.org/licenses/LICENSE-2.0                             *
//                                                                             *
// Unless required by applicable law or agreed to in writing, software         *
// distributed under the License is distributed on an "AS IS" BASIS,           *
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    *
// See the License for the specific language governing permissions and         *
// limitations under the License.                                              *
//                                                                             *
//******************************************************************************

//******************************************************************************
// sg13g2_moshv RF (NQS) paramsets
//
// Adapted from `ngspice/models/sg13g2_moshv_param.lib` modelcards
//
// NMOS and PMOS RF (NQS) paramsets are included from separate files.
// (c) Lukas Deutz 2026
//******************************************************************************

`pragma modelgen nogen-module
`include "psp103_nqs.va"

`include "paramsets/sg13g2_moshv_rf_nmos.va"
`include "paramsets/sg13g2_moshv_rf_pmos.va"
